name: Run checks
on:
    workflow_dispatch:
    push:
    pull_request:
jobs:
    cargo-check:
        name: Run cargo checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Install bun dependencies
              run: bun install
            - name: Run cargo checks
              run: cargo check

    cargo-test:
        name: Run cargo tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Install bun dependencies
              run: bun install
            - name: Run cargo tests
              run: cargo test
